### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by XynthX** [nejason57mars/mcbot#1]
WHAT DO I PUT IN PROTOCOL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by dxomg** [comment]
https://wiki.vg/Protocol_version_numbers

> WHAT DO I PUT IN PROTOCOL

https://wiki.vg/Protocol_version_numbers

**Comment by XynthX** [comment]
ok but now it's not loading the proxies and anyways why does it need proxies

**Comment by XynthX** [comment]
i have the proxies.txt

**Comment by XynthX** [comment]
now it's not joining any bots
