### ISSUE TITLE
File proxies.txt must contain list of Socks4 Proxies.

### ISSUE THREAD

**Issue by SkellC** [nejason57mars/mcbot#9]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/63358722/179392443-53d878c5-e9b9-4b85-b0f7-4f2ed786ec56.png">

**Comment by f4r2** [comment]
create file proxies.txt and put socks4 proxies

**Comment by vermax55** [comment]
> создайте файл proxies.txt и поместите в него прокси socks4

it dont works where i need to create this txt file ? It stay with the McBot.jar in one folder but this error

**Comment by eksses** [comment]
just git clone the whole folder and run it its already included with the proxy.txt 
or check my fork i had made a java gui for this https://github.com/R-Samir-Bhuiyan-A/mcbot.exe
